### ISSUE TITLE
3v or 5v

### ISSUE THREAD

**Issue by burf2000** [RickoLacharity/Neato-XV-11-LIDAR#1]
I believe their was 2 versions of the Neato?  I think Mine is 5v

Are you directly connecting it to a Arduino or did you make a circuit.

What code runs on the Arduino?

**Comment by ErikLacharite** [comment]
The motor itself is 5v for max speed, but as I did not have a motor controller I powered it off of 3.3v and that got it to the correct RPM (~200) to start returning values. 

There was no Arduino code used as I was justing using it for serial pass through by having a jumper wire between the reset pin and ground. 

If you would like to read from it using the Arduino you can use serial.read() and the baud rate of 115200  in your sketch, example here: 
[https://www.arduino.cc/en/Serial/Read](https://www.arduino.cc/en/Serial/Read)
